CREATE SEQUENCE SEQ_TB_PRODUTO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE SEQ_TB_NOTAFISCAL
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE SEQ_TB_FORNECEDOR
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

create table TB_PRODUTO(
  PRODUTO_ID NUMBER(5) NOT NULL,
  DESCRICAO VARCHAR2(30),
  UNIDADE VARCHAR2(5),
  PRECO NUMBER(10,2),
  constraint PK_TB_PRODUTO primary key(PRODUTO_ID)
);

create table TB_FORNECEDOR(
  FORNECEDOR_ID NUMBER(5) NOT NULL,
  RAZAOSOCIAL VARCHAR2(60),
  NOMEFANTASIA VARCHAR2(60),
  CNPJ VARCHAR2(18),
  constraint PK_TB_FORNECEDOR primary key(FORNECEDOR_ID)
);

create table TB_NATOPERACAO(
  CODCFO VARCHAR2(5) NOT NULL,
  DESCRICAO VARCHAR2(100),
  constraint PK_TB_NATOPERACAO primary key(CODCFO)
);

create table TB_NOTAFISCAL(
  NF_ID NUMBER(10) NOT NULL,
  FORNECEDOR_ID NUMBER(5) NOT NULL,
  NUMERO NUMBER(10) NOT NULL,
  SERIE VARCHAR2(3) NOT NULL,
  DT_EMISSAO DATE NOT NULL,
  DT_ENTRADA DATE NOT NULL,
  VR_ITENS NUMBER(14,5),
  VR_IPI NUMBER(14,5),
  VR_BASE_ICMS NUMBER(14,5),
  VR_TOTAL NUMBER(14,5),
  VR_ICMS NUMBER(14,5),
  constraint PK_TB_NOTAFISCAL primary key(NF_ID),
  constraint FK_TBNOTAFISCAL_TBFORNECEDOR foreign key(FORNECEDOR_ID) references TB_FORNECEDOR(FORNECEDOR_ID)
);

create table TB_NOTAFISCAL_ITEM(
  NF_ID NUMBER(10) NOT NULL,
  ITEM NUMBER(4) NOT NULL,
  PRODUTO_ID NUMBER(5) NOT NULL,
  QUANTIDADE NUMBER(14,5),
  VR_UNITARIO NUMBER(14,5),
  CODCFO VARCHAR2(5),
  ALIQ_IPI NUMBER(5,2),
  VR_IPI NUMBER(14,5),
  PERC_DESCONTO NUMBER(5,2),
  VR_DESCONTO NUMBER(14,5),
  ALIQ_ICMS NUMBER(5,2),
  VR_ICMS NUMBER(14,5),
  VR_TOTAL_ITEM NUMBER(14,5),
  constraint PK_TB_NOTAFISCAL_ITEM primary key(NF_ID, ITEM),
  constraint FK_TBNFITEM_TBNOTAFISCAL foreign key(NF_ID) references TB_NOTAFISCAL(NF_ID) on delete cascade,
  constraint FK_TBNFITEM_TBPRODUTO foreign key(PRODUTO_ID) references TB_PRODUTO(PRODUTO_ID),
  constraint FK_TBNFITEM_TBNATOPERACAO foreign key(CODCFO) references TB_NATOPERACAO(CODCFO)
);
