INSERT INTO TB_FORNECEDOR
VALUES(SEQ_TB_FORNECEDOR.NEXTVAL, 'FORNECEDOR  TESTE 1', 'FORNECEDOR 1', '11.111.111/1111-11');

INSERT INTO TB_FORNECEDOR
VALUES(SEQ_TB_FORNECEDOR.NEXTVAL, 'FORNECEDOR  TESTE 2', 'FORNECEDOR 2', '22.222.222/2222-22');

INSERT INTO TB_FORNECEDOR
VALUES(SEQ_TB_FORNECEDOR.NEXTVAL, 'FORNECEDOR  TESTE 3', 'FORNECEDOR 3', '33.333.333/3333-33');


INSERT INTO TB_PRODUTO
VALUES(SEQ_TB_PRODUTO.NEXTVAL, 'PRODUTO 1', 'UN', 123.4);

INSERT INTO TB_PRODUTO
VALUES(SEQ_TB_PRODUTO.NEXTVAL, 'PRODUTO 2', 'KG', 17.9);

INSERT INTO TB_PRODUTO
VALUES(SEQ_TB_PRODUTO.NEXTVAL, 'PRODUTO 3', 'LT', 45.8);

INSERT INTO TB_PRODUTO
VALUES(SEQ_TB_PRODUTO.NEXTVAL, 'PRODUTO 4', 'UN', 1.99);


INSERT INTO TB_NATOPERACAO
VALUES('5.101', 'Venda de produção do estabelecimento');

INSERT INTO TB_NATOPERACAO
VALUES('6.101', 'Venda de produção do estabelecimento interestadual');

INSERT INTO TB_NATOPERACAO
VALUES('5.911', 'Remessa de amostra grátis');

INSERT INTO TB_NATOPERACAO
VALUES('6.911', 'Remessa de amostra grátis interestadual');

INSERT INTO TB_NATOPERACAO
VALUES('5.915', 'Remessa de mercadoria ou bem para conserto ou reparo');

commit;
